# Nome do workflow
name: Challenge

# Quando o workflow será executado
on: push

# Define os jobs que existem nesse workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4 # palavra chave para evocar uma action
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
